<?php
global $_W;
$sql = "
drop table if exists " . tablename('sz_yi_adv') . " ;
drop table if exists " . tablename('sz_yi_carrier') . " ;
drop table if exists " . tablename('sz_yi_category') . " ;
drop table if exists " . tablename('sz_yi_commission_apply') . " ;
drop table if exists " . tablename('sz_yi_commission_clickcount') . " ;
drop table if exists " . tablename('sz_yi_commission_level') . " ;
drop table if exists " . tablename('sz_yi_commission_log') . " ;
drop table if exists " . tablename('sz_yi_commission_shop') . " ;
drop table if exists " . tablename('sz_yi_designer') . " ;
drop table if exists " . tablename('sz_yi_dispatch') . " ;
drop table if exists " . tablename('sz_yi_express') . " ;
drop table if exists " . tablename('sz_yi_feedback') . " ;
drop table if exists " . tablename('sz_yi_goods') . "; 
drop table if exists " . tablename('sz_yi_goods_comment') . " ;
drop table if exists " . tablename('sz_yi_goods_option') . " ;
drop table if exists " . tablename('sz_yi_goods_param') . " ;
drop table if exists " . tablename('sz_yi_goods_spec') . " ;
drop table if exists " . tablename('sz_yi_goods_spec_item') . " ;
drop table if exists " . tablename('sz_yi_member') . " ;
drop table if exists " . tablename('sz_yi_member_address') . " ;
drop table if exists " . tablename('sz_yi_member_cart') . " ;
drop table if exists " . tablename('sz_yi_member_favorite') . " ;
drop table if exists " . tablename('sz_yi_member_group') . " ;
drop table if exists " . tablename('sz_yi_member_history') . " ;
drop table if exists " . tablename('sz_yi_member_level') . " ;
drop table if exists " . tablename('sz_yi_member_log') . " ;
drop table if exists " . tablename('sz_yi_member_message_template') . " ;
drop table if exists " . tablename('sz_yi_notice') . " ;
drop table if exists " . tablename('sz_yi_order') . " ;
drop table if exists " . tablename('sz_yi_order_comment') . " ;
drop table if exists " . tablename('sz_yi_order_goods') . " ;
drop table if exists " . tablename('sz_yi_order_refund') . " ;
drop table if exists " . tablename('sz_yi_perm_log') . " ;
drop table if exists " . tablename('sz_yi_perm_plugin') . "; 
drop table if exists " . tablename('sz_yi_perm_role') . " ;
drop table if exists " . tablename('sz_yi_perm_user') . " ;
drop table if exists " . tablename('sz_yi_plugin') . " ;
drop table if exists " . tablename('sz_yi_poster') . " ;
drop table if exists " . tablename('sz_yi_poster_log') . " ;
drop table if exists " . tablename('sz_yi_poster_qr') . " ;
drop table if exists " . tablename('sz_yi_poster_scan') . " ;
drop table if exists " . tablename('sz_yi_saler') . " ;
drop table if exists " . tablename('sz_yi_store') . " ;
drop table if exists " . tablename('sz_yi_sysset') . " ;
drop table if exists " . tablename('sz_yi_creditshop_adv') . " ;
drop table if exists " . tablename('sz_yi_creditshop_category') . " ;
drop table if exists " . tablename('sz_yi_creditshop_goods') . " ;
drop table if exists " . tablename('sz_yi_creditshop_log') . " ;
drop table if exists " . tablename('sz_yi_virtual_category') . " ;
drop table if exists " . tablename('sz_yi_virtual_data') . " ;
drop table if exists " . tablename('sz_yi_virtual_type') . " ;
drop table if exists " . tablename('sz_yi_designer_menu') . " ;
drop table if exists " . tablename('sz_yi_article') . " ;
drop table if exists " . tablename('sz_yi_article_category') . " ;
drop table if exists " . tablename('sz_yi_article_log') . " ;
drop table if exists " . tablename('sz_yi_article_report') . " ;
drop table if exists " . tablename('sz_yi_article_share') . " ;
drop table if exists " . tablename('sz_yi_article_sys') . " ;
drop table if exists " . tablename('sz_yi_postera_log') . " ;
drop table if exists " . tablename('sz_yi_postera_qr') . " ;
drop table if exists " . tablename('sz_yi_coupon') . " ;
drop table if exists " . tablename('sz_yi_coupon_category') . " ;
drop table if exists " . tablename('sz_yi_coupon_data') . " ;
drop table if exists " . tablename('sz_yi_coupon_guess') . " ;
drop table if exists " . tablename('sz_yi_coupon_log') . " ;
";
pdo_query($sql);
